---
- name: molecule - prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: molecule - generate private key
      delegate_to: localhost
      community.crypto.openssl_privatekey:
        path: /tmp/server.key
        mode: "0644"
        type: RSA
        size: 2048

    - name: molecule - generate openssl csr
      delegate_to: localhost
      community.crypto.openssl_csr:
        path: /tmp/server.csr
        privatekey_path: /tmp/server.key
        common_name: localhost
        country_name: RU
        organization_name: akimrx

    - name: molecule - generate openssl x509 certificate
      delegate_to: localhost
      community.crypto.x509_certificate:
        path: /tmp/server.crt
        privatekey_path: /tmp/server.key
        csr_path: /tmp/server.csr
        provider: selfsigned

    - name: molecule - install apt packages
      become: true
      apt:
        name:
          - curl
          - cron
          - python3
          - python3-distutils
        state: present
        update_cache: true

    - name: molecule - install pip for Ubuntu 18
      become: true
      shell:
        cmd: curl -L https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

    - name: molecule - install pip for new Ubuntu
      become: true
      shell:
        cmd: curl -L https://bootstrap.pypa.io/get-pip.py | python3
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version != "18"

    - name: molecule - install python requirements
      become: true
      shell:
        cmd: pip3 install setuptools
